version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  postgres:
    image: postgres:latest
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgress
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: 'redis/redis-stack-server:latest'
    network_mode: service:app
    volumes:
      - redis-data:/redis
volumes:
  redis-data:
  postgres-data: